@startuml
!include style.puml
skinparam BoxPadding 10

box <font:Berlin Sans FB><size:28><color:Midnightblue>Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":CopyEmailCommandParser" as CopyEmailCommandParser LOGIC_COLOR
participant "c:CopyEmailCommand" as CopyEmailCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box <font:Berlin Sans FB><size:20><color:Purple>CommandManageable CM_COLOR_T1
participant ":CommandManager" as CommandManager CM_COLOR
end box

[-> LogicManager : <font Berlin Sans FB><color:black>execute("copy-email 1")</color>
activate LogicManager

LogicManager -> AddressBookParser : <font Berlin Sans FB><color:black>parseCommand("copy-email 1")
activate AddressBookParser

create CopyEmailCommandParser
AddressBookParser -> CopyEmailCommandParser
activate CopyEmailCommandParser

CopyEmailCommandParser --> AddressBookParser
deactivate CopyEmailCommandParser

AddressBookParser -> CopyEmailCommandParser : <font Berlin Sans FB><color:black>parse("1")
activate CopyEmailCommandParser

create CopyEmailCommand
CopyEmailCommandParser -> CopyEmailCommand
activate CopyEmailCommand

CopyEmailCommand --> CopyEmailCommandParser : <font Berlin Sans FB><color:black>c
deactivate CopyEmailCommand

CopyEmailCommandParser --> AddressBookParser : <font Berlin Sans FB><color:black>c
deactivate CopyEmailCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
CopyEmailCommandParser -[hidden]-> AddressBookParser
destroy CopyEmailCommandParser

AddressBookParser --> LogicManager : <font Berlin Sans FB><color:black>c
deactivate AddressBookParser

LogicManager -> CopyEmailCommand : <font Berlin Sans FB><color:black>execute()
activate CopyEmailCommand

CopyEmailCommand -> CommandManager : <font Berlin Sans FB><color:black>execute()
activate CommandManager

CommandManager --> CopyEmailCommand
deactivate CommandManager

create CommandResult
CopyEmailCommand -> CommandResult
activate CommandResult

CommandResult --> CopyEmailCommand
deactivate CommandResult

CopyEmailCommand --> LogicManager : <font Berlin Sans FB><color:black>result
deactivate CopyEmailCommand

[<--LogicManager
deactivate LogicManager
@enduml
