@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package <color:DarkGoldenRod>Storage <<Rectangle>> {

package "<color:grey>UserPrefs Storage" <<Rectangle>> STORAGE_COLOR_T1{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "<color:grey>AddressBook Storage" <<Rectangle>> STORAGE_COLOR_T1{
Class "<<interface>>\nAddressBookStorage" as AddressBookStorage
Class JsonAddressBookStorage
Class JsonSerializableAddressBook
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #Teal
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "<color:grey>1" UserPrefsStorage
StorageManager -up-> "<color:grey>1" AddressBookStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> AddressBookStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonAddressBookStorage .up.|> AddressBookStorage
JsonAddressBookStorage ..> JsonSerializableAddressBook
JsonSerializableAddressBook --> "<color:grey>*" JsonAdaptedPerson
JsonAdaptedPerson --> "<color:grey>*" JsonAdaptedTag

@enduml
