@startuml
!include style.puml
skinparam ClassFontColor #00000
skinparam ClassBorderColor #00000

title <color:#000000> After 2 undoable Commands

package <color:black>States <<rectangle>> {
    class State1 as "__ab0:AddressBook__"
    class State2 as "__ab1:AddressBook__"
    class State3 as "__ab2:AddressBook__"
}

State1 -right-> State2
State2 -right-> State3

class Pointer as "Current State" #000000

Pointer -up-> State3
@end
